#!/bin/sh

/etc/init.d/ipsec start ;
/etc/init.d/xl2tpd start ;

ipsec auto --up L2TP-PSK ;

echo "c vpn-connection" > /var/run/xl2tpd/l2tp-control ;

# ip route
sleep 2

DEFAULT_ROUTE=$(ip route show default | awk '/default/ {print $3}')
echo $DEFAULT_ROUTE;
echo $PUBLIC_IP
route add $VPN_SERVER_IP gw $DEFAULT_ROUTE
route add $PUBLIC_IP gw $DEFAULT_ROUTE

sleep 5
route add default dev ppp0
