#!/bin/sh

LOCAL_GATEWAY="10.0.0.1"
REMOTE_GATEWAY="192.168.42.1"

REMOTE_IP="88.99.13.172"
LOCAL_IP="37.46.132.56"

mkdir -p /var/run/xl2tpd ;
touch /var/run/xl2tpd/l2tp-control ;

service strongswan restart ;
service xl2tpd restart ;

ipsec up myvpn ;

echo "c myvpn" > /var/run/xl2tpd/l2tp-control ;

# ip route
sleep 2

route add $REMOTE_IP gw $LOCAL_GATEWAY
route add $LOCAL_IP gw $REMOTE_GATEWAY

sleep 5
route add default dev ppp0
