#!/bin/sh

LOCAL_GATEWAY=""
REMOTE_GATEWAY=""

REMOTE_IP=""
LOCAL_IP=""

mkdir -p /var/run/xl2tpd ;
touch /var/run/xl2tpd/l2tp-control ;

service strongswan restart ;
service xl2tpd restart ;

ipsec up myvpn ;

echo "c myvpn" > /var/run/xl2tpd/l2tp-control ;

# ip route
sleep 2

route add $REMOTE_IP gw $LOCAL_GATEWAY
route add $LOCAL_IP gw $REMOTE_GATEWAY

sleep 5
route add default dev ppp0
